services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: seismic-risk-api
    ports:
      - "8001:8001"
    networks:
      - seismic-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: seismic-risk-dashboard
    ports:
      - "8502:8502"
    environment:
      API_URL: http://seismic-risk-api:8001/predict
    depends_on:
      - api
    networks:
      - seismic-network

networks:
  seismic-network:
    driver: bridge