services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    
    ports:
      - "8001:8001"
    networks:
      - seismic-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    
    ports:
      - "8502:8502"
    environment:
      API_URL: http://api:8001/predict
    depends_on:
      - api
    networks:
      - seismic-network

networks:
  seismic-network:
    driver: bridge